name: Test workflow dispatch missing param
on:
  workflow_dispatch:
    inputs:
      test_one:
        description: 'Input one'
        required: true
        default: ''
      test_two:
        description: 'Input two'
        required: true
        default: ''
jobs:
  testing:
    runs-on: unbuntu-latest

    steps:
      - name: Validate input
        if: github.event.inputs.test_one == ''
        run: |
          echo "Missing test_one value, deployment cannot continue"
          exit 1

      - name: Continued
        run: |
          echo "If the input value was missing you should not be here"

