name: Test workflow dispatch missing param
on:
  workflow_dispatch:
    inputs:
      test_one:
        description: 'Input one'
        required: true
        default: ''
      test_two:
        description: 'Input two'
        required: true
        default: ''
jobs:
  testing:
    runs-on: ubuntu-18.04

    steps:
      - name: Validate input
        run: |
          echo "test_one value: " ${{ github.event.inputs.test_one }}
         
      - name: Continued
        run: |
          echo "If the input value was missing you should not be here"

